#!/bin/bash
###############################################################################
# Project: hi-cli
# Description: The cross platform development toolkit - hi-cli
# Author: John Deng (john.deng@outlook.com)
#
# Copyright (c) 2014-2017 John Deng (john.deng@outlook.com)
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: John Deng (john.deng@outlook.com)
# Updated: Thu Mar 23 23:09:27 CST 2017
# module: mp
# Action: help
###############################################################################

source "${HI_CLI_HOME}/bin/colors"
source "${HI_CLI_HOME}/bin/logging"
###############################################################################
function input() {
  arg_name=$2
  arg_value=$3
  default_value=$4
  if [ "${arg_value}" == "" ]; then
    def_val=""
    if [ "${arg_name}" == "password" ]; then
      def_val="[******]"
    elif [ "${default_value}" != "" ]; then
      def_val="[${default_value}]"
    fi
    read -p "$(echo -e ${DARKGREEN}[hi-cli] ${DARKTEAL}${arg_name} ${DARKBLUE}${def_val}${ENDCOLOR}): " result < /dev/tty
  else
    result=${arg_value}  
  fi
  if [ "${result}" == "" ]; then
    result=${default_value}
  fi

  log_debug "input result: ${result}"

  eval $1="\${result}"
}

###############################################################################


